### ISSUE TITLE
Why did you need a rtsp proxy?

### ISSUE THREAD

**Issue by kidmock** [goruck/alexa-ip-cam#3]
I'm very intrigued by this project. I use zoneminder for my NVR and was look to to solve the same problem as you (Show my LAN Cameras on my Echo Show).

However I'm a bit confused on why you need live555 at all.

Can't you just add your individual rtsp streams to the camera.json?

**Comment by savageautomate** [comment]
@kidmock 

I'll try to answer this question -- but @goruck may have a more specific answer.

First, you must have a TLS secured endpoint using a valid SSL certificate on port 443 with a DNS resolvable hostname.  If your Zoneminder NVR supports you installing and setting up a valid SSL certificate and secures the RTSP feeds using TLS/SSL then you may not need the RTSP proxy server.  

Your NVR also aggregates all your cameras to a single RTSP endpoint address.  Without an NVR, the RTSP proxy server helps to aggregate all the IP cameras under a single resolvable endpoint that can be secured with TLS/SSL _using Stunnel._ 

So if you can access all your cameras across RTSP URLs on your NVR, then you may be able to skip the proxy server but you will still need to secure the NVR endpoint either from its own internal support for SSL certificates or by placing Stunnel in front of the NVR.

Another potential reason for the proxy server is that not all cameras are directly compatible with Alexa's RTSP player.  Specifically Foscam and ReoLink cameras all fail without the RTSP proxy server in front of them.  See:  https://monoclecam.com/proxy-server

This is a fantastic project and it (in part) helped inspire the **Monocle** project and **Monocle Alexa Skill**.   If you want the features of this project without having to do the heavy lifting, please check out: 
https://monoclecam.com/

Thanks, Robert

**Comment by goruck** [comment]
Hey,

@kidmock is correct - the RTSP proxy aggregates the camera streams. Also correct on why stunnel needs to be used. Kind of a hack but it works. 

I use ZoneMinder as well and I did look into directly using the Alexa Smart Home Camera API with ZoneMinder but ran into problems because of the specific way that API needs to be used.

However, the Alexa Skills Kit offers another API called [VideoApp Interface](https://developer.amazon.com/docs/custom-skills/videoapp-interface-reference.html) that I have successfully  used in another project called [smart-zoneminder](https://github.com/goruck/smart-zoneminder) to enable ZoneMinder to work with Alexa (and Rekognition!). 

Hope this helps.

Lindo

**Comment by goruck** [comment]
Closing this since it looks like the question was addressed.
